name: Publish package to GitHub Packages
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "antivpn-releases",
              "username": "${{ secrets.REPO_USERNAME }}",
              "password": "${{ secrets.REPO_TOKEN }}"
            }]
      - name: Publish package
        run: mvn --batch-mode deploy
